//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSubjectHomeWork
    {
        public int Id { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> HomeWorkId { get; set; }
        public string HomeWorkDetail { get; set; }
    
        public virtual AspNetCours AspNetCours { get; set; }
        public virtual AspNetHomeWork AspNetHomeWork { get; set; }
    }
}
