//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspnetBranchClassSubjectSection
    {
        public int Id { get; set; }
        public Nullable<int> BranchClassSubjectId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual AspnetGenericBranchClassSubject AspnetGenericBranchClassSubject { get; set; }
        public virtual AspNetSection AspNetSection { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
    }
}
