//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetEmployee()
        {
            this.AspNetAccountants = new HashSet<AspNetAccountant>();
            this.EmployeeAdvanceSalaries = new HashSet<EmployeeAdvanceSalary>();
            this.EmployeeAbsentTables = new HashSet<EmployeeAbsentTable>();
            this.EmployeeAutoPresents = new HashSet<EmployeeAutoPresent>();
            this.AspNetTeacher_Enrollments = new HashSet<AspNetTeacher_Enrollments>();
            this.AspNetTeachers = new HashSet<AspNetTeacher>();
            this.EmployeePenalties = new HashSet<EmployeePenalty>();
            this.Employee_SalaryRecord = new HashSet<Employee_SalaryRecord>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.Teacher_GenericSubjects = new HashSet<Teacher_GenericSubjects>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Position { get; set; }
        public string DateAvailable { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public int NationalityId { get; set; }
        public int ReligionId { get; set; }
        public int GenderId { get; set; }
        public string CellNo { get; set; }
        public string Landline { get; set; }
        public string SpouseName { get; set; }
        public string SpouseHighestDegree { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<bool> Accomodation { get; set; }
        public Nullable<decimal> ProvidedFund { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> EOP { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string JoiningDate { get; set; }
        public string Illness { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Address { get; set; }
        public string Spouse_Address { get; set; }
        public string File { get; set; }
        public string UserId { get; set; }
        public Nullable<int> VirtualRoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAccountant> AspNetAccountants { get; set; }
        public virtual AspNetBranch AspNetBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAdvanceSalary> EmployeeAdvanceSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAbsentTable> EmployeeAbsentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAutoPresent> EmployeeAutoPresents { get; set; }
        public virtual AspNetGender AspNetGender { get; set; }
        public virtual AspNetNationality AspNetNationality { get; set; }
        public virtual AspNetEmployeePosition AspNetEmployeePosition { get; set; }
        public virtual AspNetReligion AspNetReligion { get; set; }
        public virtual AspNetVirtualRole AspNetVirtualRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Enrollments> AspNetTeacher_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher> AspNetTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePenalty> EmployeePenalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_SalaryRecord> Employee_SalaryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher_GenericSubjects> Teacher_GenericSubjects { get; set; }
    }
}
