//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetClass()
        {
            this.AspNetBranch_Class = new HashSet<AspNetBranch_Class>();
            this.AspNetClass_Courses = new HashSet<AspNetClass_Courses>();
            this.AspNetSubjects = new HashSet<AspNetSubject>();
            this.AspNetClasses1 = new HashSet<AspNetClass>();
            this.AspnetGenericBranchClassSubjects = new HashSet<AspnetGenericBranchClassSubject>();
            this.AspNetHomeWorks = new HashSet<AspNetHomeWork>();
            this.AspnetStudentAssignmentSubmissions = new HashSet<AspnetStudentAssignmentSubmission>();
            this.AspNetStudents = new HashSet<AspNetStudent>();
            this.ClassFeeTypes = new HashSet<ClassFeeType>();
            this.Class_ChallanForm = new HashSet<Class_ChallanForm>();
            this.StudentRecurringFees = new HashSet<StudentRecurringFee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> NextClassId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBranch_Class> AspNetBranch_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetClass_Courses> AspNetClass_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetSubject> AspNetSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetClass> AspNetClasses1 { get; set; }
        public virtual AspNetClass AspNetClass1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspnetGenericBranchClassSubject> AspnetGenericBranchClassSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetHomeWork> AspNetHomeWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspnetStudentAssignmentSubmission> AspnetStudentAssignmentSubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent> AspNetStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassFeeType> ClassFeeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_ChallanForm> Class_ChallanForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRecurringFee> StudentRecurringFees { get; set; }
    }
}
