//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetStudent()
        {
            this.AspNetStudent_Enrollments = new HashSet<AspNetStudent_Enrollments>();
            this.AspNetStudent_Histories = new HashSet<AspNetStudent_Histories>();
            this.AspnetStudentAssignmentSubmissions = new HashSet<AspnetStudentAssignmentSubmission>();
            this.AspNetStudentHomeWorks = new HashSet<AspNetStudentHomeWork>();
            this.Month_Multiplier = new HashSet<Month_Multiplier>();
            this.AspNetStudentSections = new HashSet<AspNetStudentSection>();
            this.Student_ChallanForm = new HashSet<Student_ChallanForm>();
            this.NonRecurringFeeMultipliers = new HashSet<NonRecurringFeeMultiplier>();
            this.NonRecurringMonths = new HashSet<NonRecurringMonth>();
            this.StudentFeeMultipliers = new HashSet<StudentFeeMultiplier>();
            this.Student_Quiz_Scoring = new HashSet<Student_Quiz_Scoring>();
            this.StudentChallanForms = new HashSet<StudentChallanForm>();
            this.StudentDiscounts = new HashSet<StudentDiscount>();
            this.StudentFeeMonths = new HashSet<StudentFeeMonth>();
            this.StudentPenalties = new HashSet<StudentPenalty>();
            this.StudentTestSubjects = new HashSet<StudentTestSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RollNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Address { get; set; }
        public string Birthdate { get; set; }
        public string CellNo { get; set; }
        public string File { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetGender AspNetGender { get; set; }
        public virtual AspNetNationality AspNetNationality { get; set; }
        public virtual AspNetReligion AspNetReligion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Enrollments> AspNetStudent_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Histories> AspNetStudent_Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspnetStudentAssignmentSubmission> AspnetStudentAssignmentSubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudentHomeWork> AspNetStudentHomeWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Month_Multiplier> Month_Multiplier { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudentSection> AspNetStudentSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_ChallanForm> Student_ChallanForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonRecurringFeeMultiplier> NonRecurringFeeMultipliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonRecurringMonth> NonRecurringMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeeMultiplier> StudentFeeMultipliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Quiz_Scoring> Student_Quiz_Scoring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChallanForm> StudentChallanForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDiscount> StudentDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeeMonth> StudentFeeMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPenalty> StudentPenalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTestSubject> StudentTestSubjects { get; set; }
    }
}
