//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetClass_Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetClass_Courses()
        {
            this.AspNetStudent_Enrollments = new HashSet<AspNetStudent_Enrollments>();
            this.AspNetTeacher_Enrollments = new HashSet<AspNetTeacher_Enrollments>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetCours AspNetCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Enrollments> AspNetStudent_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Enrollments> AspNetTeacher_Enrollments { get; set; }
    }
}
