//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetSubject()
        {
            this.AspNetStudent_Subject = new HashSet<AspNetStudent_Subject>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string TeacherID { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Subject> AspNetStudent_Subject { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
