//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspnetGenericBranchClassSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspnetGenericBranchClassSubject()
        {
            this.AspnetBranchClassSubjectSections = new HashSet<AspnetBranchClassSubjectSection>();
            this.AspnetSubjectTopics = new HashSet<AspnetSubjectTopic>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> SectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspnetBranchClassSubjectSection> AspnetBranchClassSubjectSections { get; set; }
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetCours AspNetCours { get; set; }
        public virtual AspNetSection AspNetSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspnetSubjectTopic> AspnetSubjectTopics { get; set; }
    }
}
