//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_ChallanForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class_ChallanForm()
        {
            this.Student_ChallanForm = new HashSet<Student_ChallanForm>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual DurationType DurationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_ChallanForm> Student_ChallanForm { get; set; }
    }
}
