//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTestSubject
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string StudentSubmittedTestName { get; set; }
        public string TeacherSubmittedTestName { get; set; }
        public string TeacherComments { get; set; }
        public Nullable<int> TestSubjectId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StudentSubDate { get; set; }
        public Nullable<System.DateTime> TeacherSubDate { get; set; }
        public Nullable<double> ObtainedMarks { get; set; }
    
        public virtual AspNetStudent AspNetStudent { get; set; }
        public virtual TestSubject TestSubject { get; set; }
    }
}
