//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCalendar
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string StartTimeZone { get; set; }
        public string EndTimeZone { get; set; }
        public string RecurrenceRule { get; set; }
        public string RecurrenceID { get; set; }
        public string RecurrenceException { get; set; }
        public Nullable<System.DateTime> C_Start { get; set; }
        public Nullable<System.DateTime> C_End { get; set; }
        public Nullable<bool> IsAllDay { get; set; }
    }
}
